# CodeRabbit configuration
# https://docs.coderabbit.ai/reference/configuration

reviews:
  pre_merge_checks:
    docstrings:
      # Disabled: produces false positives on refactoring PRs
      mode: off
