# Generated by Django 5.2.8 on 2025-11-15 23:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('month', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('era', models.CharField(choices=[('PM', 'Pure Mechanical'), ('EM', 'Electromechanical'), ('SS', 'Solid State')], max_length=2)),
                ('system', models.CharField(blank=True, max_length=100)),
                ('scoring', models.CharField(blank=True, max_length=100)),
                ('flipper_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pinside_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ipdb_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('production_quantity', models.CharField(blank=True, max_length=50)),
                ('factory_address', models.CharField(blank=True, max_length=300)),
                ('design_credit', models.CharField(blank=True, max_length=200)),
                ('concept_and_design_credit', models.CharField(blank=True, max_length=200)),
                ('art_credit', models.CharField(blank=True, max_length=200)),
                ('sound_credit', models.CharField(blank=True, max_length=200)),
                ('educational_text', models.TextField(blank=True)),
                ('illustration_filename', models.CharField(blank=True, max_length=255)),
                ('sources_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_models_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_models_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MachineInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name_override', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('acquisition_notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, choices=[('floor', 'Floor'), ('workshop', 'Workshop'), ('storage', 'Storage')], max_length=20)),
                ('operational_status', models.CharField(choices=[('good', 'Good'), ('unknown', 'Unknown'), ('fixing', 'Fixing'), ('broken', 'Broken')], default='unknown', max_length=20)),
                ('ownership_credit', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_instances_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_instances_updated', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='catalog.machinemodel')),
            ],
            options={
                'ordering': ['model__name', 'serial_number'],
            },
        ),
    ]
