# Generated by Django 5.2.8 on 2025-11-18 01:22

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug field for existing MachineModel records."""
    MachineModel = apps.get_model('catalog', 'MachineModel')

    for model in MachineModel.objects.all():
        base_slug = slugify(model.name) or "model"
        slug = base_slug
        counter = 2

        # Ensure unique slug
        while MachineModel.objects.filter(slug=slug).exclude(pk=model.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        model.slug = slug
        model.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    """Set all slugs to None (reverse operation)."""
    MachineModel = apps.get_model('catalog', 'MachineModel')
    MachineModel.objects.all().update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_slug_nullable'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
