# Generated by Django 5.2.8 on 2025-11-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_machineinstance_operational_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Machine location', 'verbose_name_plural': 'Machine locations'},
        ),
    ]
