# Generated by Django 5.2.8 on 2025-12-01 08:22

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_location_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMachineInstance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('slug', models.SlugField(blank=True)),
                ('name_override', models.CharField(blank=True, help_text="Give this machine a name other than the machine's model name", max_length=200, verbose_name='Name Override')),
                ('serial_number', models.CharField(blank=True, help_text='Serial number from manufacturer', max_length=100, verbose_name='Serial Number')),
                ('acquisition_notes', models.TextField(blank=True, help_text='Details about acquisition history', verbose_name='Acquisition Notes')),
                ('ownership_credit', models.CharField(blank=True, help_text='Credit for ownership', max_length=300, verbose_name='Ownership Credit')),
                ('operational_status', models.CharField(choices=[('good', 'Good'), ('fixing', 'Fixing'), ('broken', 'Broken'), ('unknown', 'Unknown')], default='unknown', help_text='Current working condition', max_length=20, verbose_name='Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, help_text='Current physical location', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.location')),
                ('model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.machinemodel')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical machine instance',
                'verbose_name_plural': 'historical machine instances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMachineModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(db_index=True, help_text='Official name of the pinball machine model', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, help_text='Company that manufactured this machine (e.g., Bally, Williams, Stern)', max_length=200)),
                ('month', models.PositiveIntegerField(blank=True, help_text='Month of manufacture (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year of manufacture', null=True)),
                ('era', models.CharField(choices=[('PM', 'Pure Mechanical'), ('EM', 'Electromechanical'), ('SS', 'Solid State')], help_text='Technology era of the machine', max_length=2)),
                ('system', models.CharField(blank=True, help_text='Electronic system type (e.g., WPC-95, System 11)', max_length=100)),
                ('scoring', models.CharField(blank=True, help_text='Scoring system type (e.g., Reel, 5 Digit, 7 Digit)', max_length=100)),
                ('flipper_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of flippers on the machine', null=True)),
                ('pinside_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Rating from Pinside (0.00-10.00)', max_digits=4, null=True)),
                ('ipdb_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='Internet Pinball Database ID number', null=True, verbose_name='IPDB ID')),
                ('production_quantity', models.CharField(blank=True, help_text='Number of units produced (e.g., ~50,000)', max_length=50, null=True)),
                ('factory_address', models.CharField(blank=True, help_text='Address where the machine was manufactured', max_length=300)),
                ('design_credit', models.CharField(blank=True, help_text='Designer(s) of the machine', max_length=200)),
                ('concept_and_design_credit', models.CharField(blank=True, help_text='Concept and design credit (if different from designer)', max_length=200)),
                ('art_credit', models.CharField(blank=True, help_text='Artist(s) who created the artwork', max_length=200)),
                ('sound_credit', models.CharField(blank=True, help_text='Sound designer(s) or composer(s)', max_length=200)),
                ('educational_text', models.TextField(blank=True, help_text='Educational description for museum visitors')),
                ('illustration_filename', models.CharField(blank=True, help_text='Filename of the illustration image', max_length=255)),
                ('sources_notes', models.TextField(blank=True, help_text='Notes about data sources and references')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical machine model',
                'verbose_name_plural': 'historical machine models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
