# Generated by Django 5.2.8 on 2025-11-18 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_make_slug_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineinstance',
            name='acquisition_notes',
            field=models.TextField(blank=True, help_text='Details about acquisition history'),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='location',
            field=models.CharField(blank=True, choices=[('floor', 'Floor'), ('workshop', 'Workshop'), ('storage', 'Storage')], help_text='Current physical location', max_length=20),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='name_override',
            field=models.CharField(blank=True, help_text='Override the model name for this specific instance (optional)', max_length=200),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='operational_status',
            field=models.CharField(choices=[('good', 'Good'), ('unknown', 'Unknown'), ('fixing', 'Fixing'), ('broken', 'Broken')], default='unknown', help_text='Current working condition', max_length=20),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='ownership_credit',
            field=models.CharField(blank=True, help_text='Credit for donation or ownership (optional)', max_length=300),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number from manufacturer (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='art_credit',
            field=models.CharField(blank=True, help_text='Artist(s) who created the artwork', max_length=200),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='concept_and_design_credit',
            field=models.CharField(blank=True, help_text='Concept and design credit (if different from designer)', max_length=200),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='design_credit',
            field=models.CharField(blank=True, help_text='Designer(s) of the machine', max_length=200),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='educational_text',
            field=models.TextField(blank=True, help_text='Educational description for museum visitors'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='era',
            field=models.CharField(choices=[('PM', 'Pure Mechanical'), ('EM', 'Electromechanical'), ('SS', 'Solid State')], help_text='Technology era of the machine', max_length=2),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='factory_address',
            field=models.CharField(blank=True, help_text='Address where the machine was manufactured', max_length=300),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='flipper_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of flippers on the machine', null=True),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='illustration_filename',
            field=models.CharField(blank=True, help_text='Filename of the illustration image', max_length=255),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='ipdb_id',
            field=models.PositiveIntegerField(blank=True, help_text='Internet Pinball Database ID number', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Company that manufactured this machine (e.g., Bally, Williams, Stern)', max_length=200),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='month',
            field=models.PositiveIntegerField(blank=True, help_text='Month of manufacture (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='name',
            field=models.CharField(help_text='Official name of the pinball machine model', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='pinside_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating from Pinside (0.00-10.00)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='production_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of units produced', null=True),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='scoring',
            field=models.CharField(blank=True, help_text='Scoring system type (e.g., Reel, 5 Digit, 7 Digit)', max_length=100),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='sound_credit',
            field=models.CharField(blank=True, help_text='Sound designer(s) or composer(s)', max_length=200),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='sources_notes',
            field=models.TextField(blank=True, help_text='Notes about data sources and references'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='system',
            field=models.CharField(blank=True, help_text='Electronic system type (e.g., WPC-95, System 11)', max_length=100),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of manufacture', null=True),
        ),
    ]
