# Generated by Django 5.2.9 on 2025-12-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add null=True to name_override before data migration."""

    dependencies = [
        ("catalog", "0005_historicalmachineinstance_historicalmachinemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmachineinstance",
            name="name_override",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Give this machine a name other than the machine's model name",
                max_length=200,
                null=True,
                verbose_name="Name Override",
            ),
        ),
        migrations.AlterField(
            model_name="machineinstance",
            name="name_override",
            field=models.CharField(
                blank=True,
                help_text="Give this machine a name other than the machine's model name",
                max_length=200,
                null=True,
                verbose_name="Name Override",
            ),
        ),
    ]
