# Generated by Django 5.2.9 on 2025-12-24 05:03

from django.db import migrations
from django.db.models import Count


def normalize_empty_to_null(apps, schema_editor):
    """Convert empty string name_override to NULL and check for duplicates."""
    MachineInstance = apps.get_model("catalog", "MachineInstance")

    # Convert empty strings to NULL
    MachineInstance.objects.filter(name_override="").update(name_override=None)

    # Fail if duplicates exist (someone must resolve manually)
    duplicates = (
        MachineInstance.objects.exclude(name_override__isnull=True)
        .values("name_override")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    if duplicates.exists():
        dupes = list(duplicates.values_list("name_override", flat=True))
        raise ValueError(f"Duplicate name_override values found: {dupes}")


def reverse_noop(apps, schema_editor):
    """No-op reverse migration - can't un-normalize NULLs to empty strings."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_historicalmachineinstance_historicalmachinemodel"),
    ]

    operations = [
        migrations.RunPython(normalize_empty_to_null, reverse_noop),
    ]
