# Generated by Django 5.2.8 on 2025-11-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_change_production_quantity_to_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemodel',
            name='ipdb_id',
            field=models.PositiveIntegerField(blank=True, help_text='Internet Pinball Database ID number', null=True, unique=True, verbose_name='IPDB ID'),
        ),
    ]
