# Generated by Django 5.2.9 on 2025-12-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_normalize_name_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmachineinstance',
            name='name_override',
            field=models.CharField(blank=True, db_index=True, help_text="Give this machine a name other than the machine's model name", max_length=200, null=True, verbose_name='Name Override'),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='name_override',
            field=models.CharField(blank=True, help_text="Give this machine a name other than the machine's model name", max_length=200, null=True, unique=True, verbose_name='Name Override'),
        ),
    ]
