# Generated by Django 5.2.8 on 2025-11-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_verbose_names_to_machine_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineinstance',
            name='name_override',
            field=models.CharField(blank=True, help_text="Give this machine a name other than the machine's model name", max_length=200, verbose_name='Name Override'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='production_quantity',
            field=models.CharField(blank=True, help_text='Number of units produced (e.g., ~5,000 or Approximate 11,000)', max_length=50, null=True),
        ),
    ]
