# Generated by Django 5.2.9 on 2025-12-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_name_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmachineinstance',
            name='short_name',
            field=models.CharField(blank=True, db_index=True, help_text='Short display name for notifications and mobile', max_length=30, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short display name for notifications and mobile', max_length=30, null=True, unique=True, verbose_name='Short Name'),
        ),
    ]
