# Generated by Django 5.2.8 on 2025-12-01 10:46

import django.db.models.deletion
import the_flip.apps.parts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_maintainer_is_shared_account"),
        ("catalog", "0004_alter_location_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "text",
                    models.TextField(
                        help_text="Description of the part needed and why."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("ordered", "Ordered"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: the machine this part is for.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="part_requests",
                        to="catalog.machineinstance",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="The maintainer who requested this part.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="part_requests",
                        to="accounts.maintainer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartRequestMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")], max_length=20
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=the_flip.apps.parts.models.part_request_media_upload_to
                    ),
                ),
                (
                    "thumbnail_file",
                    models.FileField(
                        blank=True,
                        upload_to=the_flip.apps.parts.models.part_request_media_upload_to,
                    ),
                ),
                (
                    "transcoded_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=the_flip.apps.parts.models.part_request_media_upload_to,
                    ),
                ),
                (
                    "poster_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=the_flip.apps.parts.models.part_request_media_upload_to,
                    ),
                ),
                (
                    "transcode_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("display_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "part_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="parts.partrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Part request media",
                "verbose_name_plural": "Part request media",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartRequestUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(help_text="Update text or comment.")),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("requested", "Requested"),
                            ("ordered", "Ordered"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        help_text="If set, this update changed the part request status.",
                        max_length=20,
                    ),
                ),
                (
                    "part_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="parts.partrequest",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        help_text="The maintainer who posted this update.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="part_request_updates",
                        to="accounts.maintainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Part request update",
                "verbose_name_plural": "Part request updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartRequestUpdateMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")], max_length=20
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=the_flip.apps.parts.models.part_request_update_media_upload_to
                    ),
                ),
                (
                    "thumbnail_file",
                    models.FileField(
                        blank=True,
                        upload_to=the_flip.apps.parts.models.part_request_update_media_upload_to,
                    ),
                ),
                (
                    "transcoded_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=the_flip.apps.parts.models.part_request_update_media_upload_to,
                    ),
                ),
                (
                    "poster_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=the_flip.apps.parts.models.part_request_update_media_upload_to,
                    ),
                ),
                (
                    "transcode_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("display_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="parts.partrequestupdate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Part request update media",
                "verbose_name_plural": "Part request update media",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="partrequest",
            index=models.Index(
                fields=["created_at"], name="parts_partr_created_ff06f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partrequest",
            index=models.Index(fields=["status"], name="parts_partr_status_db92d5_idx"),
        ),
    ]
