# Generated by Django 5.2.9 on 2025-12-13 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_maintainers_group'),
        ('parts', '0002_historicalpartrequestmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='requested_by_name',
            field=models.CharField(blank=True, help_text='Name when requester is not in the system.', max_length=200),
        ),
        migrations.AddField(
            model_name='partrequestupdate',
            name='posted_by_name',
            field=models.CharField(blank=True, help_text='Name when poster is not in the system.', max_length=200),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='The maintainer who requested this part.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_requests', to='accounts.maintainer'),
        ),
        migrations.AlterField(
            model_name='partrequestupdate',
            name='posted_by',
            field=models.ForeignKey(blank=True, help_text='The maintainer who posted this update.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_request_updates', to='accounts.maintainer'),
        ),
    ]
