# Generated by Django 5.2.9 on 2025-12-26 00:16

import the_flip.apps.parts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_add_name_fields_to_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartrequestmedia',
            name='thumbnail_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpartrequestupdatemedia',
            name='thumbnail_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partrequestmedia',
            name='thumbnail_file',
            field=models.FileField(blank=True, null=True, upload_to=the_flip.apps.parts.models.part_request_media_upload_to),
        ),
        migrations.AlterField(
            model_name='partrequestupdatemedia',
            name='thumbnail_file',
            field=models.FileField(blank=True, null=True, upload_to=the_flip.apps.parts.models.part_request_update_media_upload_to),
        ),
    ]
