# Generated by Django 5.2.9 on 2025-12-30 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_standardize_thumbnail_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the part was requested. Defaults to now if not specified.'),
        ),
        migrations.AddField(
            model_name='partrequestupdate',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the update was posted. Defaults to now if not specified.'),
        ),
    ]
