# Generated by Django 5.2.9 on 2025-12-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_maintainers_group'),
        ('catalog', '0014_name_not_null'),
        ('parts', '0006_backfill_occurred_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partrequest',
            options={'ordering': ['-occurred_at']},
        ),
        migrations.AlterModelOptions(
            name='partrequestupdate',
            options={'ordering': ['occurred_at'], 'verbose_name': 'Part request update', 'verbose_name_plural': 'Part request updates'},
        ),
        migrations.RemoveIndex(
            model_name='partrequest',
            name='parts_partr_created_ff06f3_idx',
        ),
        migrations.AddIndex(
            model_name='partrequest',
            index=models.Index(fields=['occurred_at'], name='parts_partr_occurre_85201b_idx'),
        ),
    ]
