# Generated by Django 5.2.9 on 2025-12-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_alter_partrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partrequestupdate',
            options={'ordering': ['-occurred_at'], 'verbose_name': 'Part request update', 'verbose_name_plural': 'Part request updates'},
        ),
        migrations.AddIndex(
            model_name='partrequestupdate',
            index=models.Index(fields=['occurred_at'], name='parts_partr_occurre_f780b8_idx'),
        ),
    ]
