# Generated by Django 5.2.9 on 2026-01-01 02:22

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_maintainers_group'),
        ('catalog', '0014_name_not_null'),
        ('parts', '0008_add_occurred_at_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPartRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('text', models.TextField(help_text='Description of the part needed and why.')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=20)),
                ('requested_by_name', models.CharField(blank=True, help_text='Name when requester is not in the system.', max_length=200)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the part was requested. Defaults to now if not specified.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional: the machine this part is for.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.machineinstance')),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The maintainer who requested this part.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.maintainer')),
            ],
            options={
                'verbose_name': 'historical part request',
                'verbose_name_plural': 'historical part requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPartRequestUpdate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('posted_by_name', models.CharField(blank=True, help_text='Name when poster is not in the system.', max_length=200)),
                ('text', models.TextField(help_text='Update text or comment.')),
                ('new_status', models.CharField(blank=True, choices=[('requested', 'Requested'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], help_text='If set, this update changed the part request status.', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the update was posted. Defaults to now if not specified.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('part_request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parts.partrequest')),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The maintainer who posted this update.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.maintainer')),
            ],
            options={
                'verbose_name': 'historical Part request update',
                'verbose_name_plural': 'historical Part request updates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
