# Generated by Django 5.2.8 on 2025-11-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_alter_webhookeventsubscription_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhooksettings',
            options={'verbose_name': 'Webhook settings', 'verbose_name_plural': 'Webhook settings'},
        ),
    ]
