# Generated by Django 5.2.8 on 2025-12-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0003_alter_webhooksettings_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhooksettings",
            name="parts_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable webhooks for part request events."
            ),
        ),
        migrations.AlterField(
            model_name="webhookeventsubscription",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("problem_report_created", "Problem Report Created"),
                    ("log_entry_created", "Log Entry Created"),
                    ("part_request_created", "Part Request Created"),
                    ("part_request_status_changed", "Part Request Status Changed"),
                    ("part_request_update_created", "Part Request Update Created"),
                ],
                max_length=50,
            ),
        ),
    ]
