# Generated by Django 5.2.8 on 2025-12-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_webhooksettings_parts_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookeventsubscription',
            name='event_type',
            field=models.CharField(choices=[('problem_report_created', 'Problem Report Created'), ('log_entry_created', 'Log Entry Created'), ('part_request_created', 'Parts Request Created'), ('part_request_status_changed', 'Parts Request Status Changed'), ('part_request_update_created', 'Parts Request Update Created')], max_length=50),
        ),
    ]
