# Generated by Django 5.2.8 on 2025-11-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintainer",
            name="is_shared_account",
            field=models.BooleanField(
                default=False,
                help_text="Shared accounts are used on workshop terminals by multiple maintainers.",
            ),
        ),
    ]
