# Generated by Django 5.2.9 on 2025-12-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_maintainer_is_shared_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintainer',
            options={'ordering': ['user__username'], 'permissions': [('can_access_maintainer_portal', 'Can access the maintainer portal')]},
        ),
    ]
