# Generated by Django 5.2.8 on 2025-11-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineInstanceAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Machine Instance',
                'verbose_name_plural': 'Machine Instances',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tickets.machineinstance',),
        ),
        migrations.CreateModel(
            name='MachineModelAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Machine Model',
                'verbose_name_plural': 'Machine Models',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tickets.machinemodel',),
        ),
    ]
