# Generated by Django 5.2.8 on 2025-12-03 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_maintainer_is_shared_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel_id",
                    models.CharField(
                        help_text="Discord channel snowflake ID.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this channel (for admin reference).",
                        max_length=100,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether to listen to this channel."
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord channel",
                "verbose_name_plural": "Discord channels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this webhook endpoint.",
                        max_length=100,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The webhook URL to send notifications to.",
                        max_length=500,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether this endpoint is active."
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhooks_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch to enable/disable all webhook notifications.",
                    ),
                ),
                (
                    "problem_reports_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable webhooks for problem report events.",
                    ),
                ),
                (
                    "log_entries_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable webhooks for log entry events."
                    ),
                ),
                (
                    "parts_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable webhooks for part request events.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook settings",
                "verbose_name_plural": "Webhook settings",
            },
        ),
        migrations.CreateModel(
            name="DiscordUserLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discord_user_id",
                    models.CharField(
                        help_text="Discord user snowflake ID.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "discord_username",
                    models.CharField(
                        help_text="Discord username (e.g., 'deanmoses').",
                        max_length=100,
                    ),
                ),
                (
                    "discord_display_name",
                    models.CharField(
                        blank=True,
                        help_text="Discord display name (e.g., 'Dean Moses').",
                        max_length=100,
                    ),
                ),
                (
                    "discord_avatar_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the user's Discord avatar.",
                        max_length=500,
                    ),
                ),
                (
                    "maintainer",
                    models.OneToOneField(
                        help_text="The maintainer this Discord user is linked to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_link",
                        to="accounts.maintainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord user link",
                "verbose_name_plural": "Discord user links",
                "ordering": ["discord_username"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEventSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("problem_report_created", "Problem Report Created"),
                            ("log_entry_created", "Log Entry Created"),
                            ("part_request_created", "Parts Request Created"),
                            (
                                "part_request_status_changed",
                                "Parts Request Status Changed",
                            ),
                            (
                                "part_request_update_created",
                                "Parts Request Update Created",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this event subscription is active.",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="discord.webhookendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["event_type"],
                "unique_together": {("endpoint", "event_type")},
            },
        ),
    ]
