# Generated by Django 5.2.8 on 2025-12-03 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("discord", "0002_remove_webhooksettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordMessageMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_message_id",
                    models.CharField(
                        help_text="Discord message snowflake ID.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord message mapping",
                "verbose_name_plural": "Discord message mappings",
                "indexes": [
                    models.Index(
                        fields=["discord_message_id"],
                        name="discord_dis_discord_c848fe_idx",
                    )
                ],
            },
        ),
    ]
