# Generated by Django 5.2.9 on 2025-12-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("discord", "0005_remove_discord_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordmessagemapping",
            name="discord_message_id",
            field=models.CharField(
                help_text="Discord message snowflake ID.", max_length=50
            ),
        ),
        migrations.AddIndex(
            model_name="discordmessagemapping",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="discord_dis_content_a9f30d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordmessagemapping",
            constraint=models.UniqueConstraint(
                fields=("discord_message_id", "content_type", "object_id"),
                name="unique_discord_message_record",
            ),
        ),
    ]
