# Generated by Django 5.2.11 on 2026-02-10 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_align_timestamp_field_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateOptionIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('record_type', models.CharField(db_index=True, max_length=50)),
                ('machine_slug', models.CharField(blank=True, max_length=200)),
                ('location_slug', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_option_index', to='wiki.wikipage')),
            ],
            options={
                'ordering': ['label'],
                'indexes': [models.Index(fields=['record_type', 'priority', 'machine_slug', 'location_slug'], name='wiki_templa_record__d8eac7_idx')],
                'unique_together': {('page', 'template_name')},
            },
        ),
    ]
