# Generated by Django 5.2.8 on 2025-11-21 23:07

import django.db.models.deletion
import flipfix.apps.maintenance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintainer_names', models.CharField(blank=True, help_text='Comma-separated names when maintainers are not in the system.', max_length=120)),
                ('text', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='catalog.machineinstance')),
                ('maintainers', models.ManyToManyField(blank=True, related_name='log_entries', to='accounts.maintainer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEntryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to=flipfix.apps.maintenance.models.log_media_upload_to)),
                ('thumbnail_file', models.FileField(blank=True, upload_to=flipfix.apps.maintenance.models.log_media_upload_to)),
                ('transcoded_file', models.FileField(blank=True, null=True, upload_to=flipfix.apps.maintenance.models.log_media_upload_to)),
                ('poster_file', models.ImageField(blank=True, null=True, upload_to=flipfix.apps.maintenance.models.log_media_upload_to)),
                ('transcode_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('display_order', models.PositiveIntegerField(blank=True, null=True)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='maintenance.logentry')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('problem_type', models.CharField(choices=[('stuck_ball', 'Stuck Ball'), ('no_credits', 'No Credits'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('reported_by_name', models.CharField(blank=True, max_length=200)),
                ('reported_by_contact', models.CharField(blank=True, max_length=200)),
                ('device_info', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to='catalog.machineinstance')),
                ('reported_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='maintenance_created_38f36f_idx'), models.Index(fields=['status'], name='maintenance_status_143f1f_idx')],
            },
        ),
    ]
