# Generated by Django 5.2.8 on 2025-11-25 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={"ordering": ["-work_date"]},
        ),
        migrations.AddField(
            model_name="logentry",
            name="work_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the work was performed. Defaults to now if not specified.",
            ),
        ),
    ]
