# Generated by Django 5.2.8 on 2025-11-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_logentry_problem_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-work_date'], 'verbose_name': 'Log entry', 'verbose_name_plural': 'Log entries'},
        ),
        migrations.AlterModelOptions(
            name='logentrymedia',
            options={'ordering': ['display_order', 'created_at'], 'verbose_name': 'Log entry media', 'verbose_name_plural': 'Log entry media'},
        ),
    ]
