# Generated by Django 5.2.9 on 2025-12-30 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_name_not_null'),
        ('maintenance', '0013_alter_problemreport_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='problemreport',
            name='maintenance_created_38f36f_idx',
        ),
        migrations.AddIndex(
            model_name='problemreport',
            index=models.Index(fields=['occurred_at'], name='maintenance_occurre_56b2b8_idx'),
        ),
    ]
