# Generated by Django 5.2.11 on 2026-02-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_add_occurred_at_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproblemreport',
            name='priority',
            field=models.CharField(choices=[('untriaged', 'Untriaged'), ('unplayable', 'Unplayable'), ('major', 'Major'), ('minor', 'Minor'), ('task', 'Task')], db_index=True, default='minor', max_length=20),
        ),
        migrations.AddField(
            model_name='problemreport',
            name='priority',
            field=models.CharField(choices=[('untriaged', 'Untriaged'), ('unplayable', 'Unplayable'), ('major', 'Major'), ('minor', 'Minor'), ('task', 'Task')], db_index=True, default='minor', max_length=20),
        ),
    ]
