#!/usr/bin/env python3
"""
Build script to generate CLAUDE.md and AGENTS.md from docs/AGENTS.src.md.

This script parses the source file and generates two output files:
- CLAUDE.md: includes START_CLAUDE...END_CLAUDE blocks, excludes START_AGENTS...END_AGENTS
- AGENTS.md: includes START_AGENTS...END_AGENTS blocks, excludes START_CLAUDE...END_CLAUDE

Usage:
    python scripts/build_agent_docs.py

The source file uses markers on their own lines:
    START_CLAUDE / END_CLAUDE - content appears only in CLAUDE.md
    START_AGENTS / END_AGENTS - content appears only in AGENTS.md
    START_IGNORE / END_IGNORE - content stripped from both (e.g., source file metadata)
"""

import re
from pathlib import Path

# Paths relative to repo root
REPO_ROOT = Path(__file__).parent.parent
SOURCE_FILE = REPO_ROOT / "docs" / "AGENTS.src.md"
CLAUDE_OUTPUT = REPO_ROOT / "CLAUDE.md"
AGENTS_OUTPUT = REPO_ROOT / "AGENTS.md"

HEADER_TEMPLATE = """\
<!-- AUTOGENERATED FILE, DO NOT EDIT DIRECTLY -->
<!-- To regenerate, run `make agent-docs` -->
<!-- Source content: docs/AGENTS.src.md -->

"""


def generate_output(source_lines: list[str], target: str) -> str:
    """
    Generate output for a specific target (CLAUDE or AGENTS).

    Args:
        source_lines: Lines from the source file
        target: Either "CLAUDE" or "AGENTS"

    Returns:
        The processed content for the target
    """
    output_lines: list[str] = []
    skip_until_end: str | None = None

    other_target = "AGENTS" if target == "CLAUDE" else "CLAUDE"

    for line in source_lines:
        stripped = line.strip()

        # Check for IGNORE markers (stripped from both outputs)
        if stripped == "START_IGNORE":
            skip_until_end = "END_IGNORE"
            continue
        elif stripped == "END_IGNORE":
            skip_until_end = None
            continue

        # Check for start markers
        if stripped == f"START_{target}":
            # Start including content for our target (skip the marker itself)
            continue
        elif stripped == f"START_{other_target}":
            # Start skipping content for other target
            skip_until_end = f"END_{other_target}"
            continue

        # Check for end markers
        if stripped == f"END_{target}":
            continue
        elif stripped == f"END_{other_target}":
            skip_until_end = None
            continue

        # Skip lines if we're in a block for the other target or in IGNORE
        if skip_until_end:
            continue

        # Include the line (either we're in our target's block or in shared content)
        output_lines.append(line)

    return "".join(output_lines)


def clean_empty_lines(content: str) -> str:
    """
    Clean up excessive empty lines that result from removing blocks.

    Reduces 3+ consecutive newlines to 2 (one blank line).
    """
    # Replace 3+ consecutive newlines with 2
    return re.sub(r"\n{3,}", "\n\n", content)


def main() -> None:
    """Main entry point."""
    if not SOURCE_FILE.exists():
        raise FileNotFoundError(f"Source file not found: {SOURCE_FILE}")

    source_content = SOURCE_FILE.read_text()
    source_lines = source_content.splitlines(keepends=True)

    # Generate CLAUDE.md
    claude_content = generate_output(source_lines, "CLAUDE")
    claude_content = clean_empty_lines(claude_content)
    claude_final = HEADER_TEMPLATE + claude_content
    CLAUDE_OUTPUT.write_text(claude_final)
    print(f"Generated: {CLAUDE_OUTPUT}")  # noqa: T201 - CLI feedback

    # Generate AGENTS.md
    agents_content = generate_output(source_lines, "AGENTS")
    agents_content = clean_empty_lines(agents_content)
    agents_final = HEADER_TEMPLATE + agents_content
    AGENTS_OUTPUT.write_text(agents_final)
    print(f"Generated: {AGENTS_OUTPUT}")  # noqa: T201 - CLI feedback


if __name__ == "__main__":
    main()
