# Generated by Django 5.2.11 on 2026-02-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_record_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_page_content', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
