# Generated by Django 5.2.8 on 2025-11-21 23:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Official name of the pinball machine model', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('manufacturer', models.CharField(blank=True, help_text='Company that manufactured this machine (e.g., Bally, Williams, Stern)', max_length=200)),
                ('month', models.PositiveIntegerField(blank=True, help_text='Month of manufacture (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year of manufacture', null=True)),
                ('era', models.CharField(choices=[('PM', 'Pure Mechanical'), ('EM', 'Electromechanical'), ('SS', 'Solid State')], help_text='Technology era of the machine', max_length=2)),
                ('system', models.CharField(blank=True, help_text='Electronic system type (e.g., WPC-95, System 11)', max_length=100)),
                ('scoring', models.CharField(blank=True, help_text='Scoring system type (e.g., Reel, 5 Digit, 7 Digit)', max_length=100)),
                ('flipper_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of flippers on the machine', null=True)),
                ('pinside_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Rating from Pinside (0.00-10.00)', max_digits=4, null=True)),
                ('ipdb_id', models.PositiveIntegerField(blank=True, help_text='Internet Pinball Database ID number', null=True, unique=True, verbose_name='IPDB ID')),
                ('production_quantity', models.CharField(blank=True, help_text='Number of units produced (e.g., ~50,000)', max_length=50, null=True)),
                ('factory_address', models.CharField(blank=True, help_text='Address where the machine was manufactured', max_length=300)),
                ('design_credit', models.CharField(blank=True, help_text='Designer(s) of the machine', max_length=200)),
                ('concept_and_design_credit', models.CharField(blank=True, help_text='Concept and design credit (if different from designer)', max_length=200)),
                ('art_credit', models.CharField(blank=True, help_text='Artist(s) who created the artwork', max_length=200)),
                ('sound_credit', models.CharField(blank=True, help_text='Sound designer(s) or composer(s)', max_length=200)),
                ('educational_text', models.TextField(blank=True, help_text='Educational description for museum visitors')),
                ('illustration_filename', models.CharField(blank=True, help_text='Filename of the illustration image', max_length=255)),
                ('sources_notes', models.TextField(blank=True, help_text='Notes about data sources and references')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_models_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_models_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MachineInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name_override', models.CharField(blank=True, help_text="Give this machine a name other than the machine's model name", max_length=200, verbose_name='Name Override')),
                ('serial_number', models.CharField(blank=True, help_text='Serial number from manufacturer', max_length=100, verbose_name='Serial Number')),
                ('acquisition_notes', models.TextField(blank=True, help_text='Details about acquisition history', verbose_name='Acquisition Notes')),
                ('ownership_credit', models.CharField(blank=True, help_text='Credit for ownership', max_length=300, verbose_name='Ownership Credit')),
                ('location', models.CharField(blank=True, choices=[('floor', 'Floor'), ('workshop', 'Workshop'), ('storage', 'Storage')], help_text='Current physical location', max_length=20)),
                ('operational_status', models.CharField(choices=[('good', 'Good'), ('unknown', 'Unknown'), ('fixing', 'Fixing'), ('broken', 'Broken')], default='unknown', help_text='Current working condition', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_instances_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_instances_updated', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='catalog.machinemodel')),
            ],
            options={
                'ordering': ['model__name', 'serial_number'],
            },
        ),
    ]
