# Generated by Django 5.2.8 on 2025-11-25 04:37

import django.db.models.deletion
from django.db import migrations, models


def seed_locations(apps, schema_editor):
    """Create initial location data."""
    Location = apps.get_model("catalog", "Location")
    locations = [
        {"name": "Floor", "slug": "floor", "sort_order": 1},
        {"name": "Hall", "slug": "hall", "sort_order": 2},
        {"name": "Workshop", "slug": "workshop", "sort_order": 3},
        {"name": "Storage", "slug": "storage", "sort_order": 4},
    ]
    for loc_data in locations:
        Location.objects.get_or_create(slug=loc_data["slug"], defaults=loc_data)


def migrate_location_data(apps, schema_editor):
    """Convert existing string location values to ForeignKey references."""
    MachineInstance = apps.get_model("catalog", "MachineInstance")
    Location = apps.get_model("catalog", "Location")

    # Map old string values to location slugs
    location_mapping = {
        "floor": "floor",
        "workshop": "workshop",
        "storage": "storage",
    }

    for machine in MachineInstance.objects.exclude(location_old="").exclude(location_old__isnull=True):
        slug = location_mapping.get(machine.location_old)
        if slug:
            try:
                location = Location.objects.get(slug=slug)
                machine.location = location
                machine.save(update_fields=["location"])
            except Location.DoesNotExist:
                pass  # Location not found, leave as null


def reverse_location_data(apps, schema_editor):
    """Convert ForeignKey back to string values."""
    MachineInstance = apps.get_model("catalog", "MachineInstance")

    for machine in MachineInstance.objects.filter(location__isnull=False):
        machine.location_old = machine.location.slug
        machine.save(update_fields=["location_old"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        # Step 1: Create the Location model
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this location",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which locations appear in lists"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        # Step 2: Seed initial location data
        migrations.RunPython(seed_locations, migrations.RunPython.noop),
        # Step 3: Rename old location field
        migrations.RenameField(
            model_name="machineinstance",
            old_name="location",
            new_name="location_old",
        ),
        # Step 4: Add new ForeignKey location field
        migrations.AddField(
            model_name="machineinstance",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Current physical location",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="machines",
                to="catalog.location",
            ),
        ),
        # Step 5: Migrate existing data
        migrations.RunPython(migrate_location_data, reverse_location_data),
        # Step 6: Remove old location field
        migrations.RemoveField(
            model_name="machineinstance",
            name="location_old",
        ),
    ]
