# Generated by Django 5.2.8 on 2025-11-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_location_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineinstance',
            name='operational_status',
            field=models.CharField(choices=[('good', 'Good'), ('fixing', 'Fixing'), ('broken', 'Broken'), ('unknown', 'Unknown')], default='unknown', help_text='Current working condition', max_length=20, verbose_name='Status'),
        ),
    ]
