# Generated by Django 5.2.9 on 2025-12-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add unique constraint after data is normalized."""

    dependencies = [
        ("catalog", "0007_normalize_name_override"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machineinstance",
            name="name_override",
            field=models.CharField(
                blank=True,
                help_text="Give this machine a name other than the machine's model name",
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Name Override",
            ),
        ),
    ]
