# Generated by Django 5.2.9 on 2025-12-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_unique_constraint_to_name_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmachineinstance',
            name='short_name',
            field=models.CharField(blank=True, db_index=True, help_text="Short unique name for notifications and mobile display (e.g., 'Eight Ball 2')", max_length=30, null=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='machineinstance',
            name='short_name',
            field=models.CharField(blank=True, help_text="Short unique name for notifications and mobile display (e.g., 'Eight Ball 2')", max_length=30, null=True, unique=True, verbose_name='Short Name'),
        ),
    ]
