# Generated by Django 5.2.9 on 2025-12-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_add_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmachineinstance',
            name='name_override',
            field=models.CharField(blank=True, db_index=True, help_text="Custom name instead of model name (e.g., 'Eight Ball Deluxe Limited Edition #2')", max_length=200, null=True, verbose_name='Name Override'),
        ),
        migrations.AlterField(
            model_name='historicalmachineinstance',
            name='short_name',
            field=models.CharField(blank=True, db_index=True, help_text="Short name for notifications and mobile (e.g., 'Eight Ball 2')", max_length=30, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='name_override',
            field=models.CharField(blank=True, help_text="Custom name instead of model name (e.g., 'Eight Ball Deluxe Limited Edition #2')", max_length=200, null=True, unique=True, verbose_name='Name Override'),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='short_name',
            field=models.CharField(blank=True, help_text="Short name for notifications and mobile (e.g., 'Eight Ball 2')", max_length=30, null=True, unique=True, verbose_name='Short Name'),
        ),
    ]
