# Generated by Django 5.2.9 on 2025-12-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_update_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmachinemodel',
            name='era',
            field=models.CharField(blank=True, choices=[('PM', 'Pure Mechanical'), ('EM', 'Electromechanical'), ('SS', 'Solid State')], help_text='Technology era of the machine', max_length=2),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='era',
            field=models.CharField(blank=True, choices=[('PM', 'Pure Mechanical'), ('EM', 'Electromechanical'), ('SS', 'Solid State')], help_text='Technology era of the machine', max_length=2),
        ),
    ]
