# Generated by Django 5.2.8 on 2025-11-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='problem_report',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='problem_report_status',
        ),
    ]
