# Generated by Django 5.2.8 on 2025-11-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_remove_logentry_problem_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='machine_status',
        ),
    ]
