# Generated by Django 5.2.8 on 2025-11-25 04:46

from django.db import migrations


def backfill_work_date(apps, schema_editor):
    """Set work_date to created_at for existing log entries."""
    LogEntry = apps.get_model("maintenance", "LogEntry")
    for entry in LogEntry.objects.all():
        entry.work_date = entry.created_at
        entry.save(update_fields=["work_date"])


def reverse_backfill(apps, schema_editor):
    """No-op reverse - data migration doesn't need to be reversed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_add_work_date"),
    ]

    operations = [
        migrations.RunPython(backfill_work_date, reverse_backfill),
    ]
