# Generated by Django 5.2.8 on 2025-11-25 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_backfill_work_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this log entry (for audit trail).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_entries_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
