# Generated by Django 5.2.8 on 2025-11-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0004_logentry_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="problem_report",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to a problem report this log entry addresses.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_entries",
                to="maintenance.problemreport",
            ),
        ),
    ]
