# Generated by Django 5.2.8 on 2025-12-02 00:47

import django.db.models.deletion
import simple_history.models
import the_flip.apps.maintenance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_historicallogentry_historicallogentrymedia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProblemReportMedia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=20)),
                ('transcode_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('display_order', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.TextField(max_length=100)),
                ('thumbnail_file', models.TextField(blank=True, max_length=100)),
                ('transcoded_file', models.TextField(blank=True, max_length=100, null=True)),
                ('poster_file', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('problem_report', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='maintenance.problemreport')),
            ],
            options={
                'verbose_name': 'historical Problem report media',
                'verbose_name_plural': 'historical Problem report media',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProblemReportMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=20)),
                ('transcode_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('display_order', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to=the_flip.apps.maintenance.models.problem_report_media_upload_to)),
                ('thumbnail_file', models.FileField(blank=True, upload_to=the_flip.apps.maintenance.models.problem_report_media_upload_to)),
                ('transcoded_file', models.FileField(blank=True, null=True, upload_to=the_flip.apps.maintenance.models.problem_report_media_upload_to)),
                ('poster_file', models.ImageField(blank=True, null=True, upload_to=the_flip.apps.maintenance.models.problem_report_media_upload_to)),
                ('problem_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='maintenance.problemreport')),
            ],
            options={
                'verbose_name': 'Problem report media',
                'verbose_name_plural': 'Problem report media',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
