# Generated by Django 5.2.9 on 2025-12-26 00:16

import the_flip.apps.maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_add_problem_report_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallogentrymedia',
            name='thumbnail_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproblemreportmedia',
            name='thumbnail_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logentrymedia',
            name='thumbnail_file',
            field=models.FileField(blank=True, null=True, upload_to=the_flip.apps.maintenance.models.log_media_upload_to),
        ),
        migrations.AlterField(
            model_name='problemreportmedia',
            name='thumbnail_file',
            field=models.FileField(blank=True, null=True, upload_to=the_flip.apps.maintenance.models.problem_report_media_upload_to),
        ),
    ]
