# Generated by Django 5.2.9 on 2025-12-26 00:17

from django.db import migrations


def backfill_empty_to_null(apps, schema_editor):
    """Convert empty string thumbnail_file values to NULL."""
    # Maintenance app models
    LogEntryMedia = apps.get_model("maintenance", "LogEntryMedia")
    ProblemReportMedia = apps.get_model("maintenance", "ProblemReportMedia")

    LogEntryMedia.objects.filter(thumbnail_file="").update(thumbnail_file=None)
    ProblemReportMedia.objects.filter(thumbnail_file="").update(thumbnail_file=None)

    # Parts app models
    PartRequestMedia = apps.get_model("parts", "PartRequestMedia")
    PartRequestUpdateMedia = apps.get_model("parts", "PartRequestUpdateMedia")

    PartRequestMedia.objects.filter(thumbnail_file="").update(thumbnail_file=None)
    PartRequestUpdateMedia.objects.filter(thumbnail_file="").update(thumbnail_file=None)


def reverse_null_to_empty(apps, schema_editor):
    """Convert NULL thumbnail_file values back to empty string."""
    LogEntryMedia = apps.get_model("maintenance", "LogEntryMedia")
    ProblemReportMedia = apps.get_model("maintenance", "ProblemReportMedia")

    LogEntryMedia.objects.filter(thumbnail_file__isnull=True).update(thumbnail_file="")
    ProblemReportMedia.objects.filter(thumbnail_file__isnull=True).update(
        thumbnail_file=""
    )

    PartRequestMedia = apps.get_model("parts", "PartRequestMedia")
    PartRequestUpdateMedia = apps.get_model("parts", "PartRequestUpdateMedia")

    PartRequestMedia.objects.filter(thumbnail_file__isnull=True).update(
        thumbnail_file=""
    )
    PartRequestUpdateMedia.objects.filter(thumbnail_file__isnull=True).update(
        thumbnail_file=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0009_standardize_thumbnail_null"),
        ("parts", "0004_standardize_thumbnail_null"),
    ]

    operations = [
        migrations.RunPython(backfill_empty_to_null, reverse_null_to_empty),
    ]
