# Generated by Django 5.2.9 on 2025-12-30 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_backfill_thumbnail_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-occurred_at'], 'verbose_name': 'Log entry', 'verbose_name_plural': 'Log entries'},
        ),
        migrations.RenameField(
            model_name='historicallogentry',
            old_name='work_date',
            new_name='occurred_at',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='work_date',
            new_name='occurred_at',
        ),
        migrations.AddField(
            model_name='historicalproblemreport',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the problem was reported. Defaults to now if not specified.'),
        ),
        migrations.AddField(
            model_name='problemreport',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the problem was reported. Defaults to now if not specified.'),
        ),
    ]
