# Generated by Django 5.2.9 on 2025-12-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_backfill_problem_report_occurred_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemreport',
            options={'ordering': ['-occurred_at']},
        ),
    ]
