# Generated by Django 5.2.9 on 2025-12-30 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_maintainers_group'),
        ('catalog', '0014_name_not_null'),
        ('maintenance', '0014_fix_problemreport_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['occurred_at'], name='maintenance_occurre_5c2fca_idx'),
        ),
    ]
