# Generated by Django 5.2.8 on 2025-11-11 09:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year of manufacture', null=True)),
                ('month', models.PositiveIntegerField(blank=True, help_text='Month of manufacture (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('era', models.CharField(choices=[('PM', 'Pure Mechanical'), ('EM', 'Electromechanical'), ('SS', 'Solid State')], help_text='Pure Mechanical, Electromechanical, or Solid State', max_length=2, verbose_name='Era')),
                ('system', models.CharField(blank=True, help_text='e.g., WPC, System 11, MPU-1', max_length=100)),
                ('scoring', models.CharField(blank=True, help_text='Display type: manual, reels, 7-segment, DMD, video', max_length=100)),
                ('flipper_count', models.CharField(blank=True, help_text='Number of flippers', max_length=10, validators=[django.core.validators.RegexValidator(message='Must be a number', regex='^\\d+$')])),
                ('pinside_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Pinside community rating', max_digits=4, null=True)),
                ('ipdb_id', models.PositiveIntegerField(blank=True, help_text='Internet Pinball Machine Database ID number', null=True, unique=True, verbose_name='IPDB ID')),
                ('production_quantity', models.CharField(blank=True, help_text="Number of units produced (e.g., '~50,000' or '1,600')", max_length=50)),
                ('factory_address', models.CharField(blank=True, help_text='Factory address where machine was manufactured', max_length=300)),
                ('design_credit', models.CharField(blank=True, help_text="Designer name (for 'Design by' credit)", max_length=200)),
                ('concept_and_design_credit', models.CharField(blank=True, help_text="Designer name (for 'Concept and design by' credit)", max_length=200)),
                ('art_credit', models.CharField(blank=True, help_text="Artist name (for 'Art by' credit)", max_length=200)),
                ('sound_credit', models.CharField(blank=True, help_text="Sound designer name (for 'Sound by' credit)", max_length=200)),
                ('educational_text', models.TextField(blank=True, help_text='Main educational/historical narrative for public display')),
                ('illustration_filename', models.CharField(blank=True, help_text="Filename for illustration (e.g., 'gobble_hole.svg')", max_length=255)),
                ('sources_notes', models.TextField(blank=True, help_text='Citations, references, and source materials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_models_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_models_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Machine Model',
                'verbose_name_plural': 'Machine Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MachineInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-friendly identifier, auto-generated from name', max_length=200, unique=True)),
                ('name_override', models.CharField(blank=True, help_text="Optional custom name. Leave blank to use the machine model's name.", max_length=200, verbose_name='Name override')),
                ('serial_number', models.CharField(blank=True, help_text='Serial number from manufacturer', max_length=100)),
                ('acquisition_notes', models.TextField(blank=True, help_text='Story of the acquisition, date acquired, source, price, initial condition etc')),
                ('ownership_credit', models.CharField(blank=True, help_text="Credit line for ownership (e.g. 'On loan from William Pietri', 'From the collection of Sam Harvey')", max_length=300)),
                ('location', models.CharField(blank=True, choices=[('floor', 'Floor'), ('storage', 'Storage'), ('workshop', 'Workshop')], help_text='Physical location', max_length=20)),
                ('operational_status', models.CharField(choices=[('good', 'Good'), ('unknown', 'Unknown'), ('fixing', 'Fixing'), ('broken', 'Broken')], db_index=True, default='unknown', help_text='Current operational condition', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_instances_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_instances_updated', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='tickets.machinemodel', verbose_name='Machine model')),
            ],
            options={
                'verbose_name': 'Machine Instance',
                'verbose_name_plural': 'Machine Instances',
                'ordering': ['model__name', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(choices=[('problem_report', 'Problem Report'), ('task', 'Task')], db_index=True, default='problem_report', help_text='Problem Report (visitor-reported) or Task (maintainer TODO)', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('reported_by_name', models.CharField(blank=True, max_length=200)),
                ('reported_by_contact', models.CharField(blank=True, help_text='Optional email/phone in case we want to follow up.', max_length=200)),
                ('device_info', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('problem_type', models.CharField(choices=[('stuck_ball', 'Stuck Ball'), ('no_credits', 'No Credits'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('problem_text', models.TextField(blank=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tickets.machineinstance')),
                ('reported_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], max_length=20, null=True)),
                ('machine_status', models.CharField(blank=True, choices=[('good', 'Good'), ('unknown', 'Unknown'), ('fixing', 'Fixing'), ('broken', 'Broken')], max_length=20, null=True)),
                ('machine', models.ForeignKey(blank=True, help_text='Machine this log entry is associated with (required for standalone logs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='tickets.machineinstance')),
                ('maintainers', models.ManyToManyField(blank=True, related_name='log_entries', to='tickets.maintainer')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='tickets.task')),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'ordering': ['created_at'],
            },
        ),
    ]
