# Generated by Django 5.2.8 on 2025-11-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineinstance',
            name='ownership_credit',
            field=models.CharField(blank=True, help_text="Credit line for ownership (e.g., 'The Flip Collection', 'On loan from William Pietri', 'From the collection of Sam Harvey')", max_length=300),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='art_credit',
            field=models.CharField(blank=True, help_text="Artist name (for 'Art by' credit)", max_length=200),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='concept_and_design_credit',
            field=models.CharField(blank=True, help_text="Designer name (for 'Concept and design by' credit)", max_length=200),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='design_credit',
            field=models.CharField(blank=True, help_text="Designer name (for 'Design by' credit)", max_length=200),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='educational_text',
            field=models.TextField(blank=True, help_text='Main educational/historical narrative for public display'),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='factory_address',
            field=models.CharField(blank=True, help_text='Factory address where machine was manufactured', max_length=300),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='illustration_filename',
            field=models.CharField(blank=True, help_text="Filename for illustration (e.g., 'gobble_hole.svg')", max_length=255),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='production_quantity',
            field=models.CharField(blank=True, help_text="Number of units produced (e.g., '~50,000' or '1,600')", max_length=50),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='sound_credit',
            field=models.CharField(blank=True, help_text="Sound designer name (for 'Sound by' credit)", max_length=200),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='sources_notes',
            field=models.TextField(blank=True, help_text='Citations, references, and source materials'),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='operational_status',
            field=models.CharField(choices=[('good', 'Good'), ('unknown', 'Unknown'), ('fixing', 'Fixing'), ('broken', 'Broken')], db_index=True, default='unknown', help_text='Current operational condition', max_length=20, verbose_name='Status'),
        ),
    ]
