# Generated by Django 5.2.8 on 2025-11-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainer',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
