# Generated by Django 5.2.8 on 2025-11-09 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_setup_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='flipper_count',
            field=models.CharField(blank=True, help_text='Number of flippers (e.g., 0, 2, 3, 4)', max_length=10, validators=[django.core.validators.RegexValidator(message='Must be a number', regex='^\\d+$')]),
        ),
        migrations.AddField(
            model_name='game',
            name='month',
            field=models.PositiveIntegerField(blank=True, help_text='Month of manufacture (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='game',
            name='pinside_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pinside rating (e.g., 8.34)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='scoring',
            field=models.CharField(blank=True, help_text='e.g., Manual, Reels, DMD, Video', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='system',
            field=models.CharField(blank=True, help_text='e.g., MPU_1, System 7, Fliptronics 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('PM', 'Pure Mechanical'), ('EM', 'Electro-Mechanical'), ('SS', 'Solid State'), ('DMD', 'Dot Matrix Display'), ('LCD', 'LCD')], max_length=4),
        ),
    ]
