# Generated by Django 5.2.8 on 2025-11-09 17:57

from django.db import migrations


def convert_mechanical_to_pm(apps, schema_editor):
    """Convert existing 'M' (Mechanical) type values to 'PM' (Pure Mechanical)"""
    Game = apps.get_model('tickets', 'Game')
    Game.objects.filter(type='M').update(type='PM')


def reverse_convert_pm_to_mechanical(apps, schema_editor):
    """Reverse migration: Convert 'PM' back to 'M'"""
    Game = apps.get_model('tickets', 'Game')
    Game.objects.filter(type='PM').update(type='M')


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_game_flipper_count_game_month_game_pinside_rating_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_mechanical_to_pm, reverse_convert_pm_to_mechanical),
    ]
