# Generated by Django 5.2.8 on 2025-11-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20251109_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('PM', 'Pure Mechanical'), ('EM', 'Electro-Mechanical'), ('SS', 'Solid State')], max_length=2),
        ),
    ]
