# Generated by Django 5.2.8 on 2025-11-09 18:07

from django.db import migrations


def convert_dmd_lcd_to_ss(apps, schema_editor):
    """Convert DMD and LCD type games to SS (Solid State) with appropriate scoring"""
    Game = apps.get_model('tickets', 'Game')

    # Convert DMD games: type -> SS, scoring -> DMD (if scoring is empty)
    dmd_games = Game.objects.filter(type='DMD')
    for game in dmd_games:
        game.type = 'SS'
        if not game.scoring:
            game.scoring = 'DMD'
        game.save()

    # Convert LCD games: type -> SS, scoring -> LCD (if scoring is empty, otherwise keep existing)
    # LCD is more specific than generic display types, so only set if empty
    lcd_games = Game.objects.filter(type='LCD')
    for game in lcd_games:
        game.type = 'SS'
        if not game.scoring:
            game.scoring = 'LCD'
        game.save()


def reverse_conversion(apps, schema_editor):
    """Reverse migration: Convert SS games back to DMD/LCD based on scoring"""
    Game = apps.get_model('tickets', 'Game')

    # Convert SS games with DMD scoring back to DMD type
    Game.objects.filter(type='SS', scoring='DMD').update(type='DMD', scoring='')

    # Convert SS games with LCD scoring back to LCD type
    Game.objects.filter(type='SS', scoring='LCD').update(type='LCD', scoring='')


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_game_type'),
    ]

    operations = [
        migrations.RunPython(convert_dmd_lcd_to_ss, reverse_conversion),
    ]
