# Generated by Django 5.2.8 on 2025-11-09 18:33

from django.db import migrations, models


def migrate_is_active_to_status(apps, schema_editor):
    """Convert is_active True/False to status good/broken"""
    Game = apps.get_model('tickets', 'Game')
    # Convert is_active=True to status='good'
    Game.objects.filter(is_active=True).update(status='good')
    # Convert is_active=False to status='broken'
    Game.objects.filter(is_active=False).update(status='broken')


def reverse_migrate_status_to_is_active(apps, schema_editor):
    """Reverse migration: Convert status back to is_active"""
    Game = apps.get_model('tickets', 'Game')
    # Convert status='good', 'unknown', 'fixing' to is_active=True
    Game.objects.filter(status__in=['good', 'unknown', 'fixing']).update(is_active=True)
    # Convert status='broken' to is_active=False
    Game.objects.filter(status='broken').update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20251109_1807'),
    ]

    operations = [
        # Step 1: Add the status field (with default='unknown')
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('good', 'Good'), ('unknown', 'Unknown'), ('fixing', 'Fixing'), ('broken', 'Broken')], db_index=True, default='unknown', max_length=20),
        ),
        # Step 2: Migrate data from is_active to status
        migrations.RunPython(migrate_is_active_to_status, reverse_migrate_status_to_is_active),
        # Step 3: Remove the is_active field
        migrations.RemoveField(
            model_name='game',
            name='is_active',
        ),
        # Step 4: Add game_status field to ReportUpdate
        migrations.AddField(
            model_name='reportupdate',
            name='game_status',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('unknown', 'Unknown'), ('fixing', 'Fixing'), ('broken', 'Broken')], max_length=20, null=True),
        ),
    ]
