# Generated by Django 5.2.8 on 2025-11-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_game_is_active_game_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ipdb_url',
            field=models.URLField(blank=True, help_text='Internet Pinball Machine Database URL', max_length=500),
        ),
    ]
