# Generated by Django 5.2.8 on 2025-11-11 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_logentry_maintainer_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['created_at'], 'verbose_name': 'Log Entry', 'verbose_name_plural': 'Log Entries'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='logentry',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Machine this log entry is associated with (required for standalone logs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='tickets.machineinstance'),
        ),
    ]
