# Generated by Django 5.2.8 on 2025-12-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebhookSettings",
        ),
    ]
