# Generated by Django 5.2.9 on 2025-12-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0004_remove_webhook_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscordChannel',
        ),
    ]
