# Generated by Django 5.2.11 on 2026-02-10 05:13

from django.db import migrations


def populate_index(apps, schema_editor):
    """Backfill TemplateOptionIndex for all existing wiki pages."""
    from the_flip.apps.wiki.actions import sync_template_option_index
    from the_flip.apps.wiki.models import WikiPage

    for page in WikiPage.objects.all():
        sync_template_option_index(page)


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0003_templateoptionindex"),
    ]

    operations = [
        migrations.RunPython(populate_index, migrations.RunPython.noop),
    ]
