# Generated by Django 5.2.11 on 2026-02-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_populate_template_option_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templateoptionindex',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='templateoptionindex',
            constraint=models.UniqueConstraint(fields=('page', 'template_name'), name='templateoptionindex_unique_page_template'),
        ),
    ]
